#pragma once

#define TMR_REG_BASE   				0x8020
#define TMR_CHANNEL_LEN				0x10

#define TMR_CONTROL_PRESCALE_1		0
#define TMR_CONTROL_PRESCALE_2		1
#define TMR_CONTROL_PRESCALE_4		2
#define TMR_CONTROL_PRESCALE_16		3

#define TMR_CONTROL_PRESCALE_SHIFT  0
#define TMR_CONTROL_PRESCALE_MASK   (3 << TMR_CONTROL_PRESCALE_SHIFT)
#define TMR_CONTROL_PRESCALE(x)     ((x) << TMR_CONTROL_PRESCALE_SHIFT)

#define TMR_CONTROL_MODE_ONCE				0
#define TMR_CONTROL_MODE_RELOAD				1
#define TMR_CONTROL_MODE_FREERUN			2
#define TMR_CONTROL_MODE_EVENTCNT			3
#define TMR_CONTROL_MODE_WATCHDOG_RESET		4
#define TMR_CONTROL_MODE_WATCHDOG_NMI		5
#define TMR_CONTROL_MODE_WATCHDOG_IRQ		6

#define TMR_CONTROL_MODE_SHIFT  	2
#define TMR_CONTROL_MODE_MASK   	(7 << TMR_CONTROL_MODE_SHIFT)
#define TMR_CONTROL_MODE(x)     	((x) << TMR_CONTROL_MODE_SHIFT)

#define TMR_CONTROL_POLARITY_NORMAL	0
#define TMR_CONTROL_POLARITY_INVERT	(1 << 6)

#define TMR_CONTROL_CLEAR_OUTPUT	(1 << 7)

#define TMR_CONTROL_PAUSE			(1 << 8)

#define TMR_CONTROL_UNFREEZE_COUNTER	(1 << 9)

#define TMR_CONTROL_RESTART			(1 << 10)

#define TMR_CONTROL_BREAKPOINT		(1 << 11)

#define TMR_CONTROL_CLOCK_EXTERNAL	(1 << 12)

#define TMR_CONTROL_UNKNOWN			(1 << 13)

#define TMR_CONTROL_AUTOCLEAR_OFF			0
#define TMR_CONTROL_AUTOCLEAR_2_CYCLES		1
#define TMR_CONTROL_AUTOCLEAR_4_CYCLES		2
#define TMR_CONTROL_AUTOCLEAR_8_CYCLES		3

#define TMR_CONTROL_AUTOCLEAR_SHIFT  14
#define TMR_CONTROL_AUTOCLEAR_MASK   (3 << TMR_CONTROL_AUTOCLEAR_SHIFT)
#define TMR_CONTROL_AUTOCLEAR(x)     ((x) << TMR_CONTROL_AUTOCLEAR_SHIFT)

#define REG_TMR_CONTROL(x)  		(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x00))
#define REG_TMR_TRIGGER(x)  		(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x02))

#define REG_TMR_RELOAD_LO(x)  		(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x04))
#define REG_TMR_RELOAD_HI(x)  		(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x06))

#define REG_TMR_COUNTER_LO(x)  		(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x08))
#define REG_TMR_COUNTER_HI(x)  		(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x0A))

#define REG_TMR_PWM_RELOAD_LO(x)	(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x0C))
#define REG_TMR_PWM_RELOAD_HI(x)  	(*(vu16*)(TMR_REG_BASE + (x) * TMR_CHANNEL_LEN + 0x0E))